/* eslint-disable max-len, no-console, require-jsdoc, curly, brace-style, block-spacing */
import {promises as fs} from "fs";
import path from "path";
import {admin} from "./adminSdk";
import {calculateMonthlyActivity} from "./monthlyCalculation";
import {storedActivityEvent} from "./persistence";
import {PublicProfileSnapshot} from "./phase2Types";

const PROJECT = "tennismate-d8acb";
const EXPECTED: Record<string, {sources: number; scoring: number; rows: number; pending: number; excluded: number; checksum: string; generation: string}> = {
  "2025-12": {sources: 1, scoring: 1, rows: 2, pending: 0, excluded: 0, checksum: "c13a59172a29b58388b3a17cf95e8c3bd2f307106408ef414f4441e7a0c3e1c8", generation: "v1-c13a59172a29b58388b3"},
  "2026-02": {sources: 2, scoring: 2, rows: 3, pending: 0, excluded: 0, checksum: "9f42508ac08d29da1921022d5b5e9bc63211445980ac42255faff1bc47696867", generation: "v1-9f42508ac08d29da1921"},
  "2026-03": {sources: 11, scoring: 9, rows: 12, pending: 0, excluded: 2, checksum: "add3e5b76fadb6ff8785436c88d429d8b26bd0ab0caaaa1b688455b3e08f8ccc", generation: "v1-add3e5b76fadb6ff8785"},
  "2026-04": {sources: 8, scoring: 5, rows: 10, pending: 2, excluded: 1, checksum: "e48d9282fdab9c5d9f5bc4ec441a159b94b91dc6087502bc6eccdf9b79815215", generation: "v1-e48d9282fdab9c5d9f5b"},
  "2026-05": {sources: 2, scoring: 2, rows: 4, pending: 0, excluded: 0, checksum: "73de8141888ba6f3a34a8397ca36776716d844d9195adb82bf5047749344334b", generation: "v1-73de8141888ba6f3a34a"},
  "2026-06": {sources: 1, scoring: 1, rows: 2, pending: 0, excluded: 0, checksum: "70ffe0d27bb85de3c7b25ad3c56e180f0c21119cd8ea076b3b9f3d345c2a629a", generation: "v1-70ffe0d27bb85de3c7b2"},
  "2026-07": {sources: 3, scoring: 1, rows: 2, pending: 2, excluded: 0, checksum: "9f8ccdd6999640ab687140b10a87e8b07526795644553268229f87816b65f49c", generation: "v1-9f8ccdd6999640ab6871"},
};
const MONTHS = Object.keys(EXPECTED).sort();
const FORBIDDEN = ["postcode", "coordinate", "latitude", "longitude", "email", "birth", "availability", "skill", "bio", "participantid", "opponentid", "sourcepath", "eventid"];
const RANKING_FIELDS = ["avatarUrl", "displayName", "distinctOpponentCount", "eligibleActivityCount", "playerId", "points", "rank", "scoringActivityCount"].sort();

function hasForbiddenKey(value: FirebaseFirestore.DocumentData): boolean {return Object.keys(value).some((key) => FORBIDDEN.some((part) => key.toLowerCase().includes(part)));}
async function profiles(db: FirebaseFirestore.Firestore, ids: string[]): Promise<Map<string, PublicProfileSnapshot>> {const result = new Map<string, PublicProfileSnapshot>(); const snapshots = ids.length ? await db.getAll(...ids.map((id) => db.doc(`players/${id}`))) : []; snapshots.forEach((snapshot) => {const data = snapshot.data() || {}; result.set(snapshot.id, {displayName: typeof data.name === "string" && data.name.trim() ? data.name.trim().slice(0, 80) : null, avatarUrl: typeof data.photoThumbURL === "string" ? data.photoThumbURL : typeof data.photoURL === "string" ? data.photoURL : typeof data.avatar === "string" ? data.avatar : null});}); return result;}

async function main(): Promise<void> {
  if (process.env.FIRESTORE_EMULATOR_HOST) throw new Error("Global production reconciliation refuses emulator state");
  const output = path.resolve(process.argv.find((arg) => arg.startsWith("--output="))?.slice(9) || "../activity-phase2-global-seven-month-reconciliation.json");
  if (admin.apps.length === 0) admin.initializeApp({projectId: PROJECT}); const db = admin.firestore();
  const [requests, monthParents, leaderboardParents, audits, allEvents] = await Promise.all([db.collection("activity_recalculation_requests").get(), db.collection("activity_months").get(), db.collection("activity_leaderboards").get(), db.collection("activity_phase2_runs").get(), db.collection("activity_match_events").get()]);
  const events = allEvents.docs.map((doc) => storedActivityEvent(doc.data())); const results = [];
  let retiredGenerationCount = 0; let totalAggregateDiscrepancies = 0; let totalLeaderboardDiscrepancies = 0; let totalStaleRows = 0; let totalMissingRows = 0;
  for (const month of MONTHS) {
    const expected = EXPECTED[month]; const monthEvents = events.filter((event) => event.monthKey === month); const provisional = calculateMonthlyActivity(monthEvents, month); const profileMap = await profiles(db, provisional.aggregates.map((row) => row.playerId)); const calculation = calculateMonthlyActivity(monthEvents, month, profileMap);
    const request = requests.docs.find((doc) => doc.id === month)?.data() || {}; const monthParent = monthParents.docs.find((doc) => doc.id === month); const leaderboardParent = leaderboardParents.docs.find((doc) => doc.id === month); const monthPointer = monthParent?.data().publishedGenerationId; const leaderboardPointer = leaderboardParent?.data().publishedGenerationId;
    const aggregateGenerations = monthParent ? await monthParent.ref.collection("generations").get() : null; const leaderboardGenerations = leaderboardParent ? await leaderboardParent.ref.collection("generations").get() : null; const aggregateGeneration = aggregateGenerations?.docs.find((doc) => doc.id === expected.generation); const leaderboardGeneration = leaderboardGenerations?.docs.find((doc) => doc.id === expected.generation); retiredGenerationCount += (aggregateGenerations?.docs.filter((doc) => doc.data().status === "RETIRED").length || 0) + (leaderboardGenerations?.docs.filter((doc) => doc.data().status === "RETIRED").length || 0);
    const aggregateRows = aggregateGeneration ? await aggregateGeneration.ref.collection("players").get() : null; const leaderboardRows = leaderboardGeneration ? await leaderboardGeneration.ref.collection("rankings").get() : null; const expectedAggregates = new Map(calculation.aggregates.map((row) => [row.playerId, row])); const expectedRankings = new Map(calculation.rankings.map((row) => [row.playerId, row]));
    let aggregateDiscrepancies = 0; for (const doc of aggregateRows?.docs || []) {const actual = doc.data(); const row = expectedAggregates.get(doc.id); if (!row || actual.eligibleActivityCount !== row.eligibleActivityCount || actual.cappedActivityCount !== row.cappedActivityCount || actual.distinctOpponentCount !== row.distinctOpponentCount || actual.activityPoints !== row.activityPoints || actual.sourceChecksum !== expected.checksum || actual.generationId !== expected.generation || actual.lastActivityAt?.toMillis?.() !== row.lastActivityAt.getTime() || hasForbiddenKey(actual)) aggregateDiscrepancies++;}
    let leaderboardDiscrepancies = 0; for (const doc of leaderboardRows?.docs || []) {const actual = doc.data(); const row = expectedRankings.get(doc.id); if (!row || actual.playerId !== row.playerId || actual.displayName !== row.displayName || actual.avatarUrl !== row.avatarUrl || actual.rank !== row.rank || actual.points !== row.activityPoints || actual.eligibleActivityCount !== row.eligibleActivityCount || actual.scoringActivityCount !== row.cappedActivityCount || actual.distinctOpponentCount !== row.distinctOpponentCount || JSON.stringify(Object.keys(actual).sort()) !== JSON.stringify(RANKING_FIELDS)) leaderboardDiscrepancies++;}
    const staleRows = (aggregateRows?.docs.filter((doc) => !expectedAggregates.has(doc.id)).length || 0) + (leaderboardRows?.docs.filter((doc) => !expectedRankings.has(doc.id)).length || 0); const missingRows = calculation.aggregates.filter((row) => !aggregateRows?.docs.some((doc) => doc.id === row.playerId)).length + calculation.rankings.filter((row) => !leaderboardRows?.docs.some((doc) => doc.id === row.playerId)).length; const monthAudits = audits.docs.filter((doc) => doc.data().month === month); const audit = monthAudits[0]?.data() || {};
    const pass = request.status === "completed" && request.attempts === 1 && calculation.sourceEventCount === expected.sources && calculation.scoringEventCount === expected.scoring && calculation.aggregates.length === expected.rows && calculation.rankings.length === expected.rows && calculation.sourceChecksum === expected.checksum && calculation.generationId === expected.generation && monthPointer === expected.generation && leaderboardPointer === expected.generation && aggregateGenerations?.size === 1 && leaderboardGenerations?.size === 1 && aggregateGeneration?.data().calculationVersion === 1 && aggregateGeneration?.data().scoringVersion === 1 && leaderboardGeneration?.data().calculationVersion === 1 && leaderboardGeneration?.data().scoringVersion === 1 && aggregateRows?.size === expected.rows && leaderboardRows?.size === expected.rows && aggregateDiscrepancies === 0 && leaderboardDiscrepancies === 0 && staleRows === 0 && missingRows === 0 && monthEvents.filter((event) => event.duplicateResolutionRole === "PENDING_REVIEW").length === expected.pending && monthEvents.filter((event) => event.duplicateResolutionRole === "EXCLUDED_DUPLICATE").length === expected.excluded && calculation.rejectedMalformedCount === 0 && monthEvents.filter((event) => event.ineligibilityReasons.includes("CANONICAL_SOURCE_CONFLICT")).length === 0 && monthAudits.length === 1 && audit.status === "COMPLETED" && audit.sourceChecksum === expected.checksum && audit.generationId === expected.generation && audit.calculationVersion === 1 && audit.scoringVersion === 1;
    totalAggregateDiscrepancies += aggregateDiscrepancies; totalLeaderboardDiscrepancies += leaderboardDiscrepancies; totalStaleRows += staleRows; totalMissingRows += missingRows; results.push({month, pass, requestStatus: request.status || null, attemptCount: request.attempts ?? null, sourceEvents: calculation.sourceEventCount, scoringEvents: calculation.scoringEventCount, aggregateRows: aggregateRows?.size || 0, leaderboardRows: leaderboardRows?.size || 0, pendingDuplicates: expected.pending, confirmedExclusions: expected.excluded, checksum: calculation.sourceChecksum, generationId: calculation.generationId, calculationVersion: aggregateGeneration?.data().calculationVersion ?? null, scoringVersion: aggregateGeneration?.data().scoringVersion ?? null, aggregateDiscrepancies, leaderboardDiscrepancies, staleRows, missingRows, auditStatus: audit.status || null, auditOrigin: audit.recordOrigin || null});
  }
  const requestStatuses = requests.docs.map((doc) => doc.data().status); const rootMonthsExact = monthParents.size === 7 && monthParents.docs.every((doc) => MONTHS.includes(doc.id)); const rootLeaderboardsExact = leaderboardParents.size === 7 && leaderboardParents.docs.every((doc) => MONTHS.includes(doc.id)); const globalPass = results.every((item) => item.pass) && requests.size === 7 && requestStatuses.every((status) => status === "completed") && rootMonthsExact && rootLeaderboardsExact && audits.size === 7 && retiredGenerationCount === 0 && totalAggregateDiscrepancies === 0 && totalLeaderboardDiscrepancies === 0 && totalStaleRows === 0 && totalMissingRows === 0;
  const report = {mode: "READ_ONLY_GLOBAL_PHASE2_RECONCILIATION", projectId: PROJECT, generatedAt: new Date().toISOString(), pass: globalPass, months: results, global: {sourceDocumentCount: allEvents.size, monthlySourceEventCount: results.reduce((sum, item) => sum + item.sourceEvents, 0), scoringEventCount: results.reduce((sum, item) => sum + item.scoringEvents, 0), recalculationRequestCount: requests.size, completedRequestCount: requestStatuses.filter((status) => status === "completed").length, pendingRequestCount: requestStatuses.filter((status) => status === "pending").length, runningRequestCount: requestStatuses.filter((status) => status === "running").length, failedRequestCount: requestStatuses.filter((status) => status === "failed").length, aggregateMonthPointerCount: monthParents.size, leaderboardMonthPointerCount: leaderboardParents.size, runAuditCount: audits.size, retiredGenerationCount, aggregateDiscrepancies: totalAggregateDiscrepancies, leaderboardDiscrepancies: totalLeaderboardDiscrepancies, staleRows: totalStaleRows, missingRows: totalMissingRows, calculationVersion: 1, scoringVersion: 1}, privacy: {containsPlayerIds: false, containsEventIds: false, containsProfileSnapshots: false, containsSourcePaths: false}};
  await fs.writeFile(output, `${JSON.stringify(report, null, 2)}\n`, "utf8"); console.log(JSON.stringify({...report, outputPath: output}, null, 2)); if (!globalPass) process.exitCode = 1;
}

main().catch((error) => {console.error(JSON.stringify({script: "verifyPhase2Global", errorCategory: error instanceof Error ? error.name : "UNKNOWN"})); process.exitCode = 1;});
